name: Backup Render PostgreSQL DB

on:
  schedule:
    - cron: '0 1 * * *'  # Every day at 1 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Dump PostgreSQL Database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          mkdir -p backup
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          FILE="pg_backup_$TIMESTAMP.sql"
          /usr/lib/postgresql/17/bin/pg_dump "$DATABASE_URL" > backup/$FILE
          echo "Backup saved to backup/$FILE"

      - name: Upload Backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup
          path: backup/
